# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import key_agent_pb2 as key__agent__pb2


class KeyAgentServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateEnvelopeKey = channel.unary_unary(
        '/kvmagent.kvmagent.keyagent.KeyAgentService/CreateEnvelopeKey',
        request_serializer=key__agent__pb2.CreateEnvelopeKeyRequest.SerializeToString,
        response_deserializer=key__agent__pb2.CreateEnvelopeKeyResponse.FromString,
        )
    self.RotateEnvelopeKey = channel.unary_unary(
        '/kvmagent.kvmagent.keyagent.KeyAgentService/RotateEnvelopeKey',
        request_serializer=key__agent__pb2.RotateEnvelopeKeyRequest.SerializeToString,
        response_deserializer=key__agent__pb2.RotateEnvelopeKeyResponse.FromString,
        )
    self.GetPublicKey = channel.unary_unary(
        '/kvmagent.kvmagent.keyagent.KeyAgentService/GetPublicKey',
        request_serializer=key__agent__pb2.GetPublicKeyRequest.SerializeToString,
        response_deserializer=key__agent__pb2.GetPublicKeyResponse.FromString,
        )
    self.CheckEnvelopeKey = channel.unary_unary(
        '/kvmagent.kvmagent.keyagent.KeyAgentService/CheckEnvelopeKey',
        request_serializer=key__agent__pb2.CheckEnvelopeKeyRequest.SerializeToString,
        response_deserializer=key__agent__pb2.CheckEnvelopeKeyResponse.FromString,
        )
    self.EnsureSecret = channel.unary_unary(
        '/kvmagent.kvmagent.keyagent.KeyAgentService/EnsureSecret',
        request_serializer=key__agent__pb2.EnsureSecretRequest.SerializeToString,
        response_deserializer=key__agent__pb2.EnsureSecretResponse.FromString,
        )


class KeyAgentServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateEnvelopeKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RotateEnvelopeKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPublicKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckEnvelopeKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnsureSecret(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeyAgentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateEnvelopeKey': grpc.unary_unary_rpc_method_handler(
          servicer.CreateEnvelopeKey,
          request_deserializer=key__agent__pb2.CreateEnvelopeKeyRequest.FromString,
          response_serializer=key__agent__pb2.CreateEnvelopeKeyResponse.SerializeToString,
      ),
      'RotateEnvelopeKey': grpc.unary_unary_rpc_method_handler(
          servicer.RotateEnvelopeKey,
          request_deserializer=key__agent__pb2.RotateEnvelopeKeyRequest.FromString,
          response_serializer=key__agent__pb2.RotateEnvelopeKeyResponse.SerializeToString,
      ),
      'GetPublicKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetPublicKey,
          request_deserializer=key__agent__pb2.GetPublicKeyRequest.FromString,
          response_serializer=key__agent__pb2.GetPublicKeyResponse.SerializeToString,
      ),
      'CheckEnvelopeKey': grpc.unary_unary_rpc_method_handler(
          servicer.CheckEnvelopeKey,
          request_deserializer=key__agent__pb2.CheckEnvelopeKeyRequest.FromString,
          response_serializer=key__agent__pb2.CheckEnvelopeKeyResponse.SerializeToString,
      ),
      'EnsureSecret': grpc.unary_unary_rpc_method_handler(
          servicer.EnsureSecret,
          request_deserializer=key__agent__pb2.EnsureSecretRequest.FromString,
          response_serializer=key__agent__pb2.EnsureSecretResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'kvmagent.kvmagent.keyagent.KeyAgentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
