# -*- coding: utf-8 -*-
"""
Endpoint registry for HTTP integration tests.

Auto-generated by evolve Round 1 (2026-03-04).
Source: scanning @replyerror decorators across all agent plugins.

Total: ~786 endpoints (607 kvmagent + 179 other agents)
"""

# kvmagent endpoints grouped by plugin
KVMAGENT_ENDPOINTS = {
    'host_plugin': {
        'sync': ['/host/connect', '/host/echo'],
        'async': ['/host/capacity', '/host/fact', '/host/ping', '/host/updateos'],
    },
    'vm_plugin': {
        'sync': ['/vm/recover/check'],
        'async': [
            '/vm/start', '/vm/stop', '/vm/reboot', '/vm/pause', '/vm/resume',
            '/vm/destroy', '/vm/migrate', '/vm/getvncport', '/vm/getdeviceaddress',
            '/vm/iso/attach', '/vm/iso/detach', '/vm/attachnic', '/vm/detachnic',
            '/vm/changenicstate', '/vm/updatenic', '/vm/usbdevice/attach',
            '/vm/usbdevice/detach', '/vm/usbdevice/reload',
            '/vm/volume/takesnapshot', '/vm/volume/mergesnapshot',
            '/vm/volume/takebackup', '/vm/volume/takecbtbackup',
            '/vm/volume/cancelcbtbackup', '/vm/volume/cancel/backupjob',
            '/vm/volume/cancel/backupjobs', '/vm/volume/takemirror',
            '/vm/volume/cancelmirror', '/vm/volume/querymirror',
            '/vm/volume/getmirrormode', '/vm/volume/blockcommit',
            '/vm/volume/blockpull', '/vm/volume/blockstream',
            '/vm/volume/checksnapshot', '/vm/volume/getvolumebitmaps',
            '/vm/volume/exportnbdvolumes', '/vm/volume/unexportnbdvolumes',
            '/vm/volume/listexportedvolumes', '/vm/volume/check',
            '/vm/volumes/takesnapshot', '/vm/volumes/takebackup',
            '/vm/recover/volumes', '/vm/vmsync', '/vm/volumesync',
            '/vm/online/changecpumem', '/vm/increase/cpu', '/vm/increase/mem',
            '/vm/apply/memory/balloon', '/vm/fstrim', '/vm/changepasswd',
            '/vm/priority', '/vm/emulatorpinning',
            '/vm/setiothreadpin', '/vm/getiothreadpin', '/vm/deliothreadpin',
            '/vm/get/cpu/xml', '/vm/compare/cpu/function',
            '/vm/getfirstbootdevice', '/vm/getvirtualizerinfo',
            '/vm/guesttools/attachiso', '/vm/guesttools/detachiso',
            '/vm/guesttools/exec', '/vm/guesttools/getinfo',
            '/vm/guesttools/getroutingstatus', '/vm/guesttools/upload_file',
            '/vm/console/harden', '/vm/console/deletefirewall',
            '/vm/console/screenshot', '/vm/clock/sync', '/vm/clock/sync/task',
            '/vm/blklivemigration', '/vm/setvfnicmac', '/vm/nodifytfnic',
            '/vm/virtio/detach', '/volume/resize',
            '/sync/vm/deviceinfo', '/primary/vm/config', '/secondary/vm/config',
            '/check/colo/vm/state', '/check/mount/domain',
            '/start/colo/sync', '/fail/colo/pvm', '/wait/colo/vm/ready',
            '/rollback/quorum/config',
            '/iscsi/target/login', '/iscsi/target/logout',
            '/vm/volume/querylatencyboundary',
        ],
    },
    'network_plugin': {
        'sync': ['/network/checkphysicalnetworkinterface'],
        'async': [],
    },
    'localstorage': {
        'async': [
            '/localstorage/init', '/localstorage/getphysicalcapacity',
            '/localstorage/checkbits', '/localstorage/delete',
            '/localstorage/deletedir', '/localstorage/unlink',
            '/localstorage/volume/createempty', '/localstorage/volume/createwithbacking',
            '/localstorage/volume/createfolder', '/localstorage/volume/createvolumefromcache',
            '/localstorage/volume/resize', '/localstorage/volume/estimatetemplatesize',
            '/localstorage/volume/getbackingchain', '/localstorage/volume/getbackingfile',
            '/localstorage/volume/getbaseimagepath',
            '/localstorage/volume/rebaserootvolumetobackingfile',
            '/localstorage/snapshot/merge', '/localstorage/snapshot/mergeandrebase',
            '/localstorage/snapshot/offlinecommit', '/localstorage/snapshot/offlinemerge',
            '/localstorage/snapshot/rebasebackingfiles', '/localstorage/snapshot/revert',
            '/localstorage/snapshot/verifychain',
            '/localstorage/reinit/image',
            '/localstorage/imagestore/commit', '/localstorage/imagestore/download',
            '/localstorage/imagestore/upload',
            '/localstorage/sftp/download', '/localstorage/sftp/upload',
            '/localstorage/kvmhost/download', '/localstorage/kvmhost/download/cancel',
            '/localstorage/kvmhost/download/progress',
            '/localstorage/copytoremote',
        ],
    },
    'nfs_primarystorage_plugin': {
        'sync': ['/nfsprimarystorage/mount', '/nfsprimarystorage/unmount'],
        'async': [
            '/nfsprimarystorage/ping', '/nfsprimarystorage/getcapacity',
            '/nfsprimarystorage/checkbits', '/nfsprimarystorage/delete',
            '/nfsprimarystorage/createemptyvolume', '/nfsprimarystorage/createvolumewithbacking',
            '/nfsprimarystorage/createfolder',
            '/nfsprimarystorage/sftp/createtemplatefromvolume',
            '/nfsprimarystorage/sftp/createvolumefromtemplate',
            '/nfsprimarystorage/volume/resize', '/nfsprimarystorage/estimatetemplatesize',
            '/nfsprimarystorage/volume/getbackingchain', '/nfsprimarystorage/getvolumesize',
            '/nfsprimarystorage/batchgetvolumesize', '/nfsprimarystorage/getvolumebaseimage',
            '/nfsprimarystorage/mergesnapshot', '/nfsprimarystorage/rebaseandmergesnapshot',
            '/nfsprimarystorage/rebasevolumebackingfile',
            '/nfsprimarystorage/revertvolumefromsnapshot',
            '/nfsprimarystorage/reinitimage', '/nfsprimarystorage/movebits',
            '/nfsprimarystorage/migratebits', '/nfsprimarystorage/unlink',
            '/nfsprimarystorage/remount', '/nfsprimarystorage/updatemountpoint',
            '/nfsprimarystorage/imagestore/commit', '/nfsprimarystorage/imagestore/download',
            '/nfsprimarystorage/imagestore/upload',
            '/nfsprimarystorage/downloadfromsftpbackupstorage',
            '/nfsprimarystorage/uploadtosftpbackupstorage',
            '/nfsprimarystorage/kvmhost/download', '/nfsprimarystorage/kvmhost/download/cancel',
            '/nfsprimarystorage/kvmhost/download/progress',
        ],
    },
    'securitygroup_plugin': {
        'async': [
            '/securitygroup/applyrules', '/securitygroup/checkdefaultrulesonhost',
            '/securitygroup/cleanupunusedrules', '/securitygroup/refreshrulesonhost',
        ],
    },
    'ha_plugin': {
        'async': [
            '/ha/selffencer/setup', '/ha/selffencer/cancel', '/ha/selffencer/state',
            '/ha/scanhost', '/ha/cbd/setupselffencer', '/ha/cbd/cancelselffencer',
            '/cbd/check/vmstate', '/ceph/host/heartbeat/check',
            '/filesystem/check/vmstate', '/iscsi/check/vmstate',
            '/sharedblock/check/vmstate', '/sanlock/scanhost',
        ],
    },
    'shared_block_plugin': {
        'async': [
            '/sharedblock/connect', '/sharedblock/disconnect', '/sharedblock/ping',
            '/sharedblock/bits/check', '/sharedblock/bits/delete',
            '/sharedblock/disks/check', '/sharedblock/disks/filter',
            '/sharedblock/vgstate/check', '/sharedblock/blockdevices',
            '/sharedblock/volume/active', '/sharedblock/volume/createempty',
            '/sharedblock/volume/createwithbacking', '/sharedblock/volume/getsize',
            '/sharedblock/volume/batchgetsize', '/sharedblock/volume/resize',
            '/sharedblock/volume/convertformat', '/sharedblock/volume/convertprovisioning',
            '/sharedblock/volume/backingchain', '/sharedblock/volume/migrate',
            '/sharedblock/volume/revertfromsnapshot',
            '/sharedblock/createrootvolume', '/sharedblock/createtemplatefromvolume',
            '/sharedblock/createimagecachefromvolume', '/sharedblock/estimatetemplatesize',
            '/sharedblock/snapshot/merge', '/sharedblock/snapshot/offlinecommit',
            '/sharedblock/snapshot/offlinemerge', '/sharedblock/snapshot/extendmergetarget',
            '/sharedblock/snapshot/shrink', '/sharedblock/logicalvolume/extend',
            '/sharedblock/imagestore/commit', '/sharedblock/imagestore/download',
            '/sharedblock/imagestore/upload',
            '/sharedblock/sftp/download', '/sharedblock/sftp/upload',
            '/sharedblock/kvmhost/download', '/sharedblock/kvmhost/download/cancel',
            '/sharedblock/kvmhost/download/progress',
        ],
    },
    'mevoco': {
        'async': [
            '/flatnetworkprovider/dhcp/apply', '/flatnetworkprovider/dhcp/batchApply',
            '/flatnetworkprovider/dhcp/batchPrepare', '/flatnetworkprovider/dhcp/connect',
            '/flatnetworkprovider/dhcp/deletenamespace', '/flatnetworkprovider/dhcp/flush',
            '/flatnetworkprovider/dhcp/prepare', '/flatnetworkprovider/dhcp/release',
            '/flatnetworkprovider/dhcp/resetDefaultGateway',
            '/flatnetworkprovider/arping',
            '/dns/forward/set', '/dns/forward/remove',
        ],
    },
}

# Non-kvmagent agent endpoints
VIRTUALROUTER_ENDPOINTS = {
    'main': {
        'async': ['/init', '/ping'],
    },
    'echo': {
        'sync': ['/echo'],
    },
    'dnsmasq': {
        'async': ['/adddhcp', '/removedhcp'],
    },
    'lb': {
        'async': ['/lb/refresh', '/lb/delete'],
    },
    'port_forwarding': {
        'async': ['/createportforwarding', '/revokeportforwarding', '/syncportforwarding'],
    },
    'snat': {
        'async': ['/setsnat', '/removesnat', '/syncsnat'],
    },
    'dns': {
        'async': ['/setdns', '/removedns'],
    },
    'eip': {
        'async': ['/createeip', '/removeeip', '/synceip'],
    },
    'vip': {
        'async': ['/createvip', '/removevip'],
    },
    'configure_nic': {
        'async': ['/configurenic'],
    },
}

APPLIANCEVM_ENDPOINTS = {
    'main': {
        'sync': ['/appliancevm/echo'],
        'async': ['/appliancevm/init', '/appliancevm/refreshfirewall'],
    },
}

CEPHBACKUP_ENDPOINTS = {
    'main': {
        'sync': ['/ceph/backupstorage/echo'],
        'async': [
            '/ceph/backupstorage/init', '/ceph/backupstorage/connect',
            '/ceph/backupstorage/ping', '/ceph/backupstorage/facts',
            '/ceph/backupstorage/image/download', '/ceph/backupstorage/image/delete',
            '/ceph/backupstorage/image/getsize', '/ceph/backupstorage/image/progress',
            '/ceph/backupstorage/image/migrate',
            '/ceph/backupstorage/image/export/addtoken',
            '/ceph/backupstorage/image/export/removetoken',
            '/ceph/backupstorage/getimagesmetadata',
            '/ceph/backupstorage/checkimagemetadatafileexist',
            '/ceph/backupstorage/dumpimagemetadatatofile',
            '/ceph/backupstorage/deleteimagesmetadata',
            '/ceph/backupstorage/checkpool',
            '/ceph/backupstorage/getlocalfilesize/',
            '/job/cancel',
        ],
    },
}

CEPHPRIMARY_ENDPOINTS = {
    'main': {
        'sync': ['/ceph/primarystorage/echo'],
        'async': [
            '/ceph/primarystorage/init', '/ceph/primarystorage/connect',
            '/ceph/primarystorage/ping', '/ceph/primarystorage/facts',
            '/ceph/primarystorage/addpool', '/ceph/primarystorage/checkpool',
            '/ceph/primarystorage/delete', '/ceph/primarystorage/deleteimagecache',
            '/ceph/primarystorage/volume/createempty', '/ceph/primarystorage/volume/clone',
            '/ceph/primarystorage/volume/flatten', '/ceph/primarystorage/volume/resize',
            '/ceph/primarystorage/volume/cp',
            '/ceph/primarystorage/getvolumesize', '/ceph/primarystorage/batchgetvolumesize',
            '/ceph/primarystorage/getvolumewatchers',
            '/ceph/primarystorage/getvolumesnapshotsize',
            '/ceph/primarystorage/volume/getbackingchain',
            '/ceph/primarystorage/volume/deletechain',
            '/ceph/primarystorage/volume/getsnapinfos',
            '/ceph/primarystorage/snapshot/commit', '/ceph/primarystorage/snapshot/create',
            '/ceph/primarystorage/snapshot/delete', '/ceph/primarystorage/snapshot/protect',
            '/ceph/primarystorage/snapshot/unprotect', '/ceph/primarystorage/snapshot/rollback',
            '/ceph/primarystorage/snapshot/checkbits',
            '/ceph/primarystorage/volume/purgesnapshots',
            '/ceph/primarystorage/volume/takebackup',
            '/ceph/primarystorage/volume/cancelbackup',
            '/ceph/primarystorage/volume/getbackupmode',
            '/ceph/primarystorage/volume/cleanbackupcache',
            '/ceph/primarystorage/volume/migratesegment',
            '/ceph/primarystorage/imagestore/backupstorage/commit',
            '/ceph/primarystorage/imagestore/backupstorage/download',
            '/ceph/primarystorage/sftpbackupstorage/download',
            '/ceph/primarystorage/sftpbackupstorage/upload',
            '/ceph/primarystorage/kvmhost/download',
            '/ceph/primarystorage/kvmhost/download/cancel',
            '/ceph/primarystorage/kvmhost/download/progress',
            '/ceph/primarystorage/nbd/download',
            '/ceph/primarystorage/remotetarget/download',
            '/ceph/primarystorage/trash/clean',
            '/job/cancel',
        ],
    },
}

CONSOLEPROXY_ENDPOINTS = {
    'main': {
        'sync': ['/console/ping'],
        'async': ['/console/check', '/console/establish', '/console/delete'],
    },
}

SFTPBACKUP_ENDPOINTS = {
    'main': {
        'sync': ['/sftpbackupstorage/connect', '/sftpbackupstorage/echo'],
        'async': [
            '/sftpbackupstorage/ping', '/sftpbackupstorage/download',
            '/sftpbackupstorage/delete', '/sftpbackupstorage/sshkey',
            '/sftpbackupstorage/getimagesize', '/sftpbackupstorage/getlocalfilesize',
            '/sftpbackupstorage/gethash',
            '/sftpbackupstorage/writeimagemetadata',
            '/sftpbackupstorage/generateimagemetadatafile',
            '/sftpbackupstorage/checkimagemetadatafileexist',
            '/sftpbackupstorage/dumpimagemetadatatofile',
            '/sftpbackupstorage/deleteimagesmetadata',
            '/sftpbackupstorage/getimagesmetadata',
            '/job/cancel',
        ],
    },
}

BAREMETALPXE_ENDPOINTS = {
    'main': {
        'sync': ['/baremetal/pxeserver/echo', '/baremetal/pxeserver/connect'],
        'async': [
            '/baremetal/pxeserver/init', '/baremetal/pxeserver/ping',
            '/baremetal/pxeserver/start', '/baremetal/pxeserver/stop',
            '/baremetal/pxeserver/createbmconfigs', '/baremetal/pxeserver/deletebmconfigs',
            '/baremetal/pxeserver/createbmnginxproxy', '/baremetal/pxeserver/deletebmnginxproxy',
            '/baremetal/pxeserver/createbmnovncproxy', '/baremetal/pxeserver/deletebmnovncproxy',
            '/baremetal/pxeserver/createdhcpconfig', '/baremetal/pxeserver/deletedhcpconfig',
            '/baremetal/pxeserver/imagestore/download', '/baremetal/pxeserver/cephb/download',
            '/baremetal/pxeserver/deletecache', '/baremetal/pxeserver/mountcache',
        ],
    },
}

# Agent port mapping
AGENT_PORTS = {
    'kvmagent': 7070,
    'virtualrouter': 7272,
    'appliancevm': 7759,
    'cephbackup': 7761,
    'cephprimary': 7762,
    'consoleproxy': 7758,
    'sftpbackupstorage': 7171,
    'baremetalpxeserver': 7770,
}

# Smoke test priority: endpoints safe to test with empty/minimal body
# These should return 200 (async accepted) or 4xx (missing params) but never crash
SMOKE_SAFE_ENDPOINTS = {
    'kvmagent': [
        # Host - always safe, read-only queries
        '/host/ping', '/host/capacity', '/host/fact', '/host/echo',
        # VM - read-only queries
        '/vm/getvncport', '/vm/getdeviceaddress', '/vm/getvirtualizerinfo',
        '/vm/get/cpu/xml', '/vm/getfirstbootdevice',
        '/vm/guesttools/getinfo', '/vm/guesttools/getroutingstatus',
        '/vm/vmsync', '/vm/volumesync',
        # Storage - read-only queries
        '/localstorage/getphysicalcapacity', '/localstorage/checkbits',
        '/nfsprimarystorage/ping', '/nfsprimarystorage/getcapacity',
        '/nfsprimarystorage/checkbits',
        '/sharedblock/ping', '/sharedblock/bits/check',
        '/sharedblock/disks/check', '/sharedblock/vgstate/check',
        # Network
        '/network/checkphysicalnetworkinterface',
        # Security group
        '/securitygroup/checkdefaultrulesonhost',
        # HA
        '/ha/selffencer/state',
    ],
    'virtualrouter': ['/echo', '/ping'],
    'appliancevm': ['/appliancevm/echo'],
    'cephbackup': ['/ceph/backupstorage/echo', '/ceph/backupstorage/ping',
                    '/ceph/backupstorage/facts'],
    'cephprimary': ['/ceph/primarystorage/echo', '/ceph/primarystorage/ping',
                     '/ceph/primarystorage/facts'],
    'consoleproxy': ['/console/ping'],
    'sftpbackupstorage': ['/sftpbackupstorage/echo', '/sftpbackupstorage/ping'],
    'baremetalpxeserver': ['/baremetal/pxeserver/echo', '/baremetal/pxeserver/ping'],
}
